### ISSUE TITLE
the example in the readme

### ISSUE THREAD

**Issue by OnlywaitY** [MrKai77/DynamicNotchKit#1]
I saw this example in the readme and I really like it, is this just a gif for display? Or do you have the source code to achieve this effect through this project? Can you provide it? Thank you for your help.
![battery](https://github.com/MrKai77/DynamicNotchKit/assets/31655270/429c21fc-c4c5-416a-9c20-ee5cbeda7b14)

**Comment by MrKai77** [comment]
Sure! You can achieve this effect like this:
```swift
let view = ProgressRing(to: .constant(0.8), color: .green)
    .overlay {
        Text("80%")
            .font(.caption)
            .foregroundStyle(.secondary)
    }

let dynamicNotch = DynamicNotchInfo(
    iconView: view,
    title: title,
    description: description
)

dynamicNotch?.show(for: seconds)
```
I haven't documented `ProgressRing` in depth yet, but it is included in the project :)

Let me know if you have any other questions!
