### ISSUE TITLE
Show Notch on multiple screens

### ISSUE THREAD

**Issue by mjn2max** [MrKai77/DynamicNotchKit#18]
Given I have a Macbook connected to two external monitors. Does the libs support to show the Notch on multiple screens at the same time?

I've thought of trying the below code but the Notch just shows on the last screen:
```swift
for screen in NSScreen.screens {
    notch.show(on: screen, for: 3)
}
```

**Comment by MrKai77** [comment]
You can initiate a new dynamicNotch for each new screen, then show them on their respective screens :)

**Comment by mjn2max** [comment]
Worked, thanks ☺️!!!
```swift
for screen in NSScreen.screens {
    let notch = DynamicNotchInfo(
        icon: Image(systemName: "figure"),
        title: "Figure",
        description: "Looks like a person"
    )
    notch.show(on: screen, for: 3)
}
```
