### ISSUE TITLE
using DNK

### ISSUE THREAD

**Issue by gitultra75848** [MrKai77/DynamicNotchKit#6]
sup, i have this code so far

`import SwiftUI
import DynamicNotchKit

  let notch = DynamicNotchInfo(
    systemImage: "figure",
    title: "Figure",
    description: "Looks like a person"
  )
  notch.show(for: 2)`

this is basically my first time using swift/swiftui so my bad if this is an easy fix.
on "notch.show(for: 2)" it says
`Expressions are not allowed at the top level.`
and on "import DynamicNotchKit" it says
`No such module "DymanicNotchKit"`
(yeah, i added it as a dependancy.)
how do i fix this?

**Comment by MrKai77** [comment]
When you add DynamicNotchKit into the project, you will need to add the scheme itself as a target. 

As for the `Expressions are not allowed at the top level.`, it means that you cannot simply call DynamicNotchKit from the top level. Since you are using SwiftUI, you will need to put it inside a view.

Anyways, if this is your first time using Swift, I would highly recommend going through some tutorials to get used to Swift before trying to use DynamicNotchKit :)

**Comment by gitultra75848** [comment]
my bad, i figured out how to fix the expression error after posting this. also, i've watched some swift tutorials after this and still can't figure out how to add "the scheme itself as a target", am i watching the wrong tutorial or?

**Comment by MrKai77** [comment]
Make sure that when adding the package, you have selected the target (sorry not scheme) as so: 
<img width="712" alt="image" src="https://github.com/MrKai77/DynamicNotchKit/assets/68963405/85c1c0fa-59cb-4e7f-90ca-4a1317042730">

**Comment by gitultra75848** [comment]
okay, that fixed it, but of course with every good thing theres a bad thing, lol.. when i did that, this error came out of nowhere, i searched reddit, stackoverflow, hacking with swift, etc and cant find a fix that would suit this.
<img width="676" alt="Screenshot 2024-05-10 at 5 22 13 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/dd7ffae1-42f8-4fea-a66c-79e3828e68e3">
my bad if im asking too many questions.

**Comment by MrKai77** [comment]
Since you are using SwiftUI, you will need to wrap it inside something like a button:
```swift
Button {
	let notch = DynamicNotchInfo(
		systemImage： "figure"，
		title： "Figure"，
		description： "Looks like a person"
	)
	notch.show(for: 2)
}, label: {
	Text("Show")
}
```

(there may be typos here)

**Comment by gitultra75848** [comment]
er, yeah soo..
<img width="676" alt="Screenshot 2024-05-10 at 5 39 12 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/a8b9b265-49bc-401e-8e9a-1218e0f17ce1">
fun, is there a different way?

**Comment by MrKai77** [comment]
Yes, you will need to wrap the button in a SwiftUI view

Check these (just from a quick search):
- https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-and-compose-custom-views
- https://developer.apple.com/documentation/swiftui/view

**Comment by gitultra75848** [comment]
appears im not understanding something, neither of these really make me understand what im supposed to do here, do you mind explaining?

**Comment by MrKai77** [comment]
It will look something like this.

```swift
import SwiftUI
import DynamicNotchKit

struct ContentView: View {
	var body: some View {
		Button {
			let notch = DynamicNotchInfo(
				systemImage： "figure"，
				title： "Figure"，
				description： "Looks like a person"
			)
			notch.show(for: 2)
		}, label: {
			Text("Show")
		}
	}
}
```

Again, I would highly recommend getting comfortable with using SwiftUI by itself before trying to learn how to use DynamicNotchKit :)

**Comment by gitultra75848** [comment]
i got it working, but just a question. how do i stop it from sliding in from the left and make it emerge only from the notch?

**Comment by MrKai77** [comment]
That shouldnt' be happening.. would yo be able to send your code?

**Comment by gitultra75848** [comment]
yeah, it's really just normal code. 
just was testing, if you want i can send a screen recording too.
summary; i made a project, imported DNK, made a playground in the project, put the code, and it didn't give me any errors except for this glitch.

`import SwiftUI
import DynamicNotchKit

let notch = DynamicNotchInfo(
    systemImage: "sparkles",
    title: "testing",
    description: "working"
)
notch.show(for: 2)
`

**Comment by MrKai77** [comment]
I haven't tried using DynamicNotchKit from a swift playground, but *maybe* it might work if you make it run asynchronously using `DispatchQueue.main.async { <DynamicNotchKit code> }`? But I'm not sure, since I never intended for this to be run from a playground.

**Comment by gitultra75848** [comment]
awesome, it works now. question though, can i make it topmost above all windows? when i switch windows (stage manager) while it's showing, the window infront overlaps the dynamic notch and goes over it.

**Comment by MrKai77** [comment]
Ohh that's interesting.. Right [here](https://github.com/MrKai77/DynamicNotchKit/blob/f4cdca7bcb28e7bd0edb98bcf8d64888e1f86d6e/Sources/DynamicNotchKit/DynamicNotch.swift#L189), the dynamicNotch is set to be on the screensaver level (one of the highest levels for a window), so I'm not exactly sure why that would be happening.

This would be a super hacky solution atm, but try adding this right after initializing the dynamicNotch, but before showing it:
```swift
notch.windowController?.window?.level = window.Level(rawValue: NSWindow.Level.RawValue(CGShieldingWindowLevel()))
```
This would set the window to be on the highest possible level, which might fix the stage manager issue.

**Comment by gitultra75848** [comment]
> Ohh that's interesting.. Right [here](https://github.com/MrKai77/DynamicNotchKit/blob/f4cdca7bcb28e7bd0edb98bcf8d64888e1f86d6e/Sources/DynamicNotchKit/DynamicNotch.swift#L189), the dynamicNotch is set to be on the screensaver level (one of the highest levels for a window), so I'm not exactly sure why that would be happening.
> 
> "This would be a super hacky solution atm, but try adding this right after initializing the dynamicNotch, but before showing it:"
> 
> ```swift
> notch.windowController?.window?.level = window.Level(rawValue: NSWindow.Level.RawValue(CGShieldingWindowLevel()))
> ```
> 
> This would set the window to be on the highest possible level, which might fix the stage manager issue.

and where would this go? before "notch.show(for: 2)"?

**Comment by MrKai77** [comment]
Yup!

**Comment by gitultra75848** [comment]
> Yup!

alright, i'll try it.

**Comment by gitultra75848** [comment]
<img width="964" alt="Screenshot 2024-05-11 at 5 11 26 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/c29b6040-cbe9-4a69-9a1b-142bcd64279c">
hmm, doesn't seem to work. do i have to import something?

**Comment by MrKai77** [comment]
Hmm.. try typing the `windowController` then the `.`, and see what autocompletion options come up. Maybe there's something similar to `window` that comes up?

**Comment by gitultra75848** [comment]
> Hmm.. try typing the `windowController` then the `.`, and see what autocompletion options come up. Maybe there's something similar to `window` that comes up?

like this?

import SwiftUI
import DynamicNotchKit

DispatchQueue.main.async {
    let notch = DynamicNotchInfo(
        systemImage: "sparkles",
        title: "testing",
        description: "working"
    )
    notch.windowController.window?.level = window.Level(rawValue: NSWindow.Level.RawValue(CGShieldingWindowLevel()))
    notch.show(for: 5)
 }

**Comment by MrKai77** [comment]
seems good to me!

**Comment by gitultra75848** [comment]
> seems good to me!

mm, okay. it gives me this.
<img width="964" alt="Screenshot 2024-05-11 at 5 27 09 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/735606fa-74f4-4895-a063-e5c14d54f094">

**Comment by MrKai77** [comment]
Try chaining the optional using the `?` and see what happens

**Comment by gitultra75848** [comment]
<img width="964" alt="Screenshot 2024-05-11 at 5 29 51 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/0791ba0d-6813-4aa1-a102-c6f1a50fd5d2">
you mean this?

**Comment by MrKai77** [comment]
Yes, and then remove `window?.level` and see what autocompletion can give you as an equivalent

**Comment by gitultra75848** [comment]
<img width="964" alt="Screenshot 2024-05-11 at 5 33 24 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/8cbf0cc9-e9f5-40a5-a686-937a70bd9fc3">
same thing.

**Comment by MrKai77** [comment]
ohhh whoops I had a typo :P

It's `NSWindow.Level`, not `window.Level`

**Comment by gitultra75848** [comment]
<img width="964" alt="Screenshot 2024-05-11 at 5 36 15 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/0617c32d-e9de-4135-8eca-839f436b49a2">

**Comment by MrKai77** [comment]
Try `NSWindow.Level(.init(CGShieldingWindowLevel()))` instead of `window.Level(rawValue: RawValue(CGShieldingWindowLevel()))`

**Comment by gitultra75848** [comment]
<img width="964" alt="Screenshot 2024-05-11 at 5 40 13 PM" src="https://github.com/MrKai77/DynamicNotchKit/assets/157659892/b5477d2e-9985-478f-83b9-14586ce1381f">
cheers!

**Comment by gitultra75848** [comment]
> Try `NSWindow.Level(.init(CGShieldingWindowLevel()))` instead of `window.Level(rawValue: RawValue(CGShieldingWindowLevel()))`

nevermind. 😄 

https://github.com/MrKai77/DynamicNotchKit/assets/157659892/b164a12e-c4c9-47ee-98c3-4081e103c07c

**Comment by MrKai77** [comment]
Nooo 😭

But it works correctly without stage manager when switching windows right? In that case, I'm confident that this is a MacOS bug.

**Comment by gitultra75848** [comment]
> Nooo 😭
> 
> But it works correctly without stage manager when switching windows right? In that case, I'm confident that this is a MacOS bug.

nope, doesn't work without stage manager either..

**Comment by MrKai77** [comment]
Alright, then it might be something with the project being a playground? Maybe since the popup is treated as an app window rather than a popuver.

Try putting the code inside a SwiftUI button and activate it from there maybe?

**Comment by gitultra75848** [comment]
> Alright, then it might be something with the project being a playground? Maybe since the popup is treated as an app window rather than a popuver.
> 
> Try putting the code inside a SwiftUI button and activate it from there maybe?

what should i put it as instead of a project? like, do i put it in a project? a workspace? and what do i put the code in? contentview.swift or?

**Comment by MrKai77** [comment]
Yes, the code would be put in ContentView (or any other SwiftUI view).

**Comment by gitultra75848** [comment]
> Yes, the code would be put in ContentView (or any other SwiftUI view).

kay, and just a normal project?
(target = app)

**Comment by gitultra75848** [comment]
> I haven't tried using DynamicNotchKit from a swift playground, but _maybe_ it might work if you make it run asynchronously using `DispatchQueue.main.async { <DynamicNotchKit code> }`? But I'm not sure, since I never intended for this to be run from a playground.

quick question, is it possible to have the dynamic notch appear when my cursor goes into it? (similar to mediamate.)

**Comment by MrKai77** [comment]
Yes, you can call notch.checkIfMouseIsInNotch() to check if the mouse is inside the notch.
