### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rishaandesai** [MrKai77/DynamicNotchKit#8]
Hello! Could you also share the source of the examples you shared in the media folder? Would love to try some of them out.

**Comment by MrKai77** [comment]
Sure, I will consider that!

**Comment by rishaandesai** [comment]
Awesome, thank you so much!

**Comment by rishaandesai** [comment]
Hey! Just wanted to follow up on this :)

**Comment by MrKai77** [comment]
Sorry, still on vacation for another 2 weeks 😉

**Comment by rishaandesai** [comment]
Thanks for the update! Have a good time 😁

**Comment by MrKai77** [comment]
Here are the two main examples!
- https://github.com/MrKai77/AudioOutputDetector
- https://github.com/MrKai77/BatteryMonitor

The window management demo is something I plan to add to [Loop](https://github.com/MrKai77/Loop), so that source may be available publicly in the future!

**Comment by rishaandesai** [comment]
Aweome! Thanks for sharing!
